require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmergenciasController do

  # This should return the minimal set of attributes required to create a valid
  # Emergencia. As you add validations to Emergencia, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      nombre: 'an emergency name',
      resumen: 'an emergency abstract',
      descripcion: 'an emergency description'
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EmergenciasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all emergencias as @emergencias" do
      emergencia = Emergencia.create! valid_attributes
      get :index, {}, valid_session
      assigns(:emergencias).should eq([emergencia])
    end
  end

  describe "GET show" do
    it "assigns the requested emergencia as @emergencia" do
      emergencia = Emergencia.create! valid_attributes
      get :show, {:id => emergencia.to_param}, valid_session
      assigns(:emergencia).should eq(emergencia)
    end
  end

  describe "GET new" do
    it "assigns a new emergencia as @emergencia" do
      get :new, {}, valid_session
      assigns(:emergencia).should be_a_new(Emergencia)
    end
  end

  describe "GET edit" do
    it "assigns the requested emergencia as @emergencia" do
      emergencia = Emergencia.create! valid_attributes
      get :edit, {:id => emergencia.to_param}, valid_session
      assigns(:emergencia).should eq(emergencia)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Emergencia" do
        expect {
          post :create, {:emergencia => valid_attributes}, valid_session
        }.to change(Emergencia, :count).by(1)
      end

      it "assigns a newly created emergencia as @emergencia" do
        post :create, {:emergencia => valid_attributes}, valid_session
        assigns(:emergencia).should be_a(Emergencia)
        assigns(:emergencia).should be_persisted
      end

      it "redirects to the created emergencia" do
        post :create, {:emergencia => valid_attributes}, valid_session
        response.should redirect_to(Emergencia.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved emergencia as @emergencia" do
        # Trigger the behavior that occurs when invalid params are submitted
        Emergencia.any_instance.stub(:save).and_return(false)
        post :create, {:emergencia => {}}, valid_session
        assigns(:emergencia).should be_a_new(Emergencia)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Emergencia.any_instance.stub(:save).and_return(false)
        post :create, {:emergencia => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested emergencia" do
        emergencia = Emergencia.create! valid_attributes
        # Assuming there are no other emergencias in the database, this
        # specifies that the Emergencia created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Emergencia.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => emergencia.to_param, :emergencia => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested emergencia as @emergencia" do
        emergencia = Emergencia.create! valid_attributes
        put :update, {:id => emergencia.to_param, :emergencia => valid_attributes}, valid_session
        assigns(:emergencia).should eq(emergencia)
      end

      it "redirects to the emergencia" do
        emergencia = Emergencia.create! valid_attributes
        put :update, {:id => emergencia.to_param, :emergencia => valid_attributes}, valid_session
        response.should redirect_to(emergencia)
      end
    end

    describe "with invalid params" do
      it "assigns the emergencia as @emergencia" do
        emergencia = Emergencia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Emergencia.any_instance.stub(:save).and_return(false)
        put :update, {:id => emergencia.to_param, :emergencia => {}}, valid_session
        assigns(:emergencia).should eq(emergencia)
      end

      it "re-renders the 'edit' template" do
        emergencia = Emergencia.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Emergencia.any_instance.stub(:save).and_return(false)
        put :update, {:id => emergencia.to_param, :emergencia => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested emergencia" do
      emergencia = Emergencia.create! valid_attributes
      expect {
        delete :destroy, {:id => emergencia.to_param}, valid_session
      }.to change(Emergencia, :count).by(-1)
    end

    it "redirects to the emergencias list" do
      emergencia = Emergencia.create! valid_attributes
      delete :destroy, {:id => emergencia.to_param}, valid_session
      response.should redirect_to(emergencias_url)
    end
  end

end
