require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportesController do

  # This should return the minimal set of attributes required to create a valid
  # Transporte. As you add validations to Transporte, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      nombre: 'a transport name',
      resumen: 'a transportt abstract',
      descripcion: 'a transportt description',
      horarios: 'a text to show the schedule'
      clasificacion: 3
    }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransportesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all transportes as @transportes" do
      transporte = Transporte.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transportes).should eq([transporte])
    end
  end

  describe "GET show" do
    it "assigns the requested transporte as @transporte" do
      transporte = Transporte.create! valid_attributes
      get :show, {:id => transporte.to_param}, valid_session
      assigns(:transporte).should eq(transporte)
    end
  end

  describe "GET new" do
    it "assigns a new transporte as @transporte" do
      get :new, {}, valid_session
      assigns(:transporte).should be_a_new(Transporte)
    end
  end

  describe "GET edit" do
    it "assigns the requested transporte as @transporte" do
      transporte = Transporte.create! valid_attributes
      get :edit, {:id => transporte.to_param}, valid_session
      assigns(:transporte).should eq(transporte)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Transporte" do
        expect {
          post :create, {:transporte => valid_attributes}, valid_session
        }.to change(Transporte, :count).by(1)
      end

      it "assigns a newly created transporte as @transporte" do
        post :create, {:transporte => valid_attributes}, valid_session
        assigns(:transporte).should be_a(Transporte)
        assigns(:transporte).should be_persisted
      end

      it "redirects to the created transporte" do
        post :create, {:transporte => valid_attributes}, valid_session
        response.should redirect_to(Transporte.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transporte as @transporte" do
        # Trigger the behavior that occurs when invalid params are submitted
        Transporte.any_instance.stub(:save).and_return(false)
        post :create, {:transporte => {}}, valid_session
        assigns(:transporte).should be_a_new(Transporte)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Transporte.any_instance.stub(:save).and_return(false)
        post :create, {:transporte => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transporte" do
        transporte = Transporte.create! valid_attributes
        # Assuming there are no other transportes in the database, this
        # specifies that the Transporte created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Transporte.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => transporte.to_param, :transporte => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested transporte as @transporte" do
        transporte = Transporte.create! valid_attributes
        put :update, {:id => transporte.to_param, :transporte => valid_attributes}, valid_session
        assigns(:transporte).should eq(transporte)
      end

      it "redirects to the transporte" do
        transporte = Transporte.create! valid_attributes
        put :update, {:id => transporte.to_param, :transporte => valid_attributes}, valid_session
        response.should redirect_to(transporte)
      end
    end

    describe "with invalid params" do
      it "assigns the transporte as @transporte" do
        transporte = Transporte.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Transporte.any_instance.stub(:save).and_return(false)
        put :update, {:id => transporte.to_param, :transporte => {}}, valid_session
        assigns(:transporte).should eq(transporte)
      end

      it "re-renders the 'edit' template" do
        transporte = Transporte.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Transporte.any_instance.stub(:save).and_return(false)
        put :update, {:id => transporte.to_param, :transporte => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transporte" do
      transporte = Transporte.create! valid_attributes
      expect {
        delete :destroy, {:id => transporte.to_param}, valid_session
      }.to change(Transporte, :count).by(-1)
    end

    it "redirects to the transportes list" do
      transporte = Transporte.create! valid_attributes
      delete :destroy, {:id => transporte.to_param}, valid_session
      response.should redirect_to(transportes_url)
    end
  end

end
